### ISSUE TITLE
Puścić każdy algorytm 5 razy na każdej reprezentacji

### ISSUE THREAD

**Issue by er713** [er713/Schooling-RL#52]
### **Ustalimy podział po 6.01 na skończeniu milestone: Przed spotkaniem z Pearsonem**

@aizemski: Skrypt uruchamiający, wpisanie parametrów
@er713: AC i DQN na RNN
@linek150: DQN tablica i nlast  
@kivix221: AC tablica i nlast 

**Parametry**:
Liczba skilli: 1 oraz 2.
timeToExam: liczba skilli*6
Liczba iteracji: 
 table: 600
 nLast: 600
 CNN: 400
Liczba studentów: 100
Epsilon: 0.9
Decay_epsilon: 0.9999
Min_epsilon:0.001
Gamma:0.99  
Lr=0.001
nLast=4*nSkills
DQN:
memsize=2048
batch_size= 256
target_iter=8192
learn_=128 (liczba rekordów dodanych do pamięci po której następuję uczenie sieci)

Na 11.01.2022r. - 20:00 Spotkanie
Link do prezki: 
https://docs.google.com/presentation/d/1LFmai02KZbGL3waXhG_2SZOcUhp8HmQ0xNqRWQ5CA3g/edit?usp=sharing

**Comment by er713** [comment]
Trzeba ustalić dla jakiej liczby skilli odpalamy modele
Rozważyć, czy np. dla 1 skilla 1000 to nie overkill

**Comment by aizemski** [comment]
Folder with colab https://drive.google.com/drive/u/0/folders/1JucoWl0kfE32uFFZVK-BBdhFlbBm3F6O
Colab: https://colab.research.google.com/drive/1-DJT_umMK4f5NOWNQWrSXK7bUWhWa3nn#scrollTo=Sb6eLyrE_bAA
